package com.caseware.tracker.service;

import com.caseware.tracker.model.TemplateVersion;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class TemplateEvaluationService {

    /**
     * Compares the engagement's current version against the latest available global template.
     * Handles accumulated updates gracefully.
     */
    public Map<String, Object> evaluateEngagementUpdate(
            String engagementId,
            String productId,
            String currentEngagementVersion,
            TemplateVersion latestGlobalTemplate,
            String aiHumanReadableSummary) {

        Map<String, Object> evaluationResult = new HashMap<>();
        evaluationResult.put("engagementId", engagementId);
        evaluationResult.put("productId", productId);
        evaluationResult.put("installedVersion", currentEngagementVersion);
        evaluationResult.put("latestAvailableVersion", latestGlobalTemplate.getVersionId());

        boolean hasPendingUpdate = !currentEngagementVersion.equals(latestGlobalTemplate.getVersionId());
        evaluationResult.put("hasPendingUpdate", hasPendingUpdate);

        if (hasPendingUpdate) {
            // Provides accumulated context and human-readable summary generated by LLM
            evaluationResult.put("summaryOfChanges", aiHumanReadableSummary);
            evaluationResult.put("publishedAt", latestGlobalTemplate.getPublishedAt());
        } else {
            evaluationResult.put("summaryOfChanges", "Engagement is up to date.");
        }

        return evaluationResult;
    }
}
